### ISSUE TITLE
Public IP support for config

### ISSUE THREAD

**Issue by camjac251** [gorcon/rcon-cli#14]
I am having trouble with getting a public IP to work on my config. It works when I call the variables directly but when it's in the config, it tries to map from my local IP I guess.

Here's what my config looks like
```yaml
default:
  address: "123.123.123.0:28016"
  password: "password"
  type: "rust"
```
and the output when I try running the default and manually

```bat
C:\Users\User>rcon -c status
read tcp 192.168.1.2:4719->123.123.123.0:28016: i/o timeout
```

```bat
C:\Users\User>rcon -a 123.123.123.0:28016 -p password -t web -c status
hostname: hi there
rest here
```
