### ISSUE TITLE
No longer works with Rust 

### ISSUE THREAD

**Issue by rknetwork** [gorcon/rcon-cli#32]
```
default:
  address: "127.0.0.1:28016" # host:port, for example 127.0.0.1:16260
  password: "test1234"
  log: "rcon-default.log"
  type: "web" # rcon, telnet, web.
  timeout: "10s"

```

```
C:\rustserver>rcon test
cli: execute: auth: rcon: rcon: read packet size: read tcp 127.0.0.1:64172->127.0.0.1:28016: i/o timeout
```
