### ISSUE TITLE
Is it really work with Palwolrd?

### ISSUE THREAD

**Issue by Miuzarte** [gorcon/rcon-cli#35]
Both Single mode and Interactive mode will report `i/o timeout` and exit after executing the command and printing the output.
![image](https://github.com/gorcon/rcon-cli/assets/66856838/7f068014-d492-4762-880f-8acfe6cf90d7)

rcon.yaml
```
palworld:
  address: "192.168.1.110:25575"
  password: "xxx"
  log: "palworldRCON.log"
  type: "rcon"
  timeout: "1s"
```
