### ISSUE TITLE
PalWorld i/o timeout

### ISSUE THREAD

**Issue by XBisATrouble** [gorcon/rcon-cli#36]
```
➜  rcon ./rcon
Waiting commands for 127.0.0.1:25575 (or type :q to exit)
> showplayers
name,playeruid,steamid
**,**,**
cli: execute: rcon: read tcp 127.0.0.1:33370->127.0.0.1:25575: i/o timeout
➜  rcon
```
ENV

Ubuntu 22.4

rcon.yaml
```
default:
  address: "127.0.0.1:25575" # host:port, for example 127.0.0.1:16260
  password: ""
  log: "rcon-default.log"
  type: "" # rcon, telnet, web.
  timeout: "60s"
```
