### ISSUE TITLE
Tilde expansion or $HOME inside config

### ISSUE THREAD

**Issue by danielwerg** [gorcon/rcon-cli#56]
While `rcon -c ~/.config/rcon-cli/rcon.yml -e name --log ~/.local/state/rcon-cli/name.log` works it would be preferable to define log path inside config.

```
name:
  address: "127.0.0.1"
  password: "PASS"
  type: "rcon"
  log: "~/.local/state/rcon-cli/name.log"
```

None of the following works:

```
log: "~/.local/state/rcon-cli/name.log"
log: "$HOME/.local/state/rcon-cli/name.log"
log: ~/.local/state/rcon-cli/name.log
log: $HOME/.local/state/rcon-cli/name.log
```

related: #45
